#!/usr/bin/env ruby

require_relative '../gems/bundler/setup'

lib_dir = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift lib_dir unless $LOAD_PATH.include?(lib_dir)

require 'account_component'

require 'component_host'

ComponentHost.start('account-component') do |host|
  host.register(AccountComponent::Start)
end
